extends Node

signal on_give_small_invent_small_item (item : Item, amount : int)
signal on_give_small_invent_medium_item (item : Item, amount : int)
signal on_give_small_invent_large_item (item : Item, amount : int)
signal on_give_med_invent_small_item (item : Item, amount : int)
signal on_give_med_invent_medium_item (item : Item, amount : int)
signal on_give_med_invent_large_item (item : Item, amount : int)
signal on_give_large_invent_small_item (item : Item, amount : int)
signal on_give_large_invent_medium_item (item : Item, amount : int)
signal on_give_large_invent_large_item (item : Item, amount : int)
signal on_briefcase_open()
signal on_medium_suitcase_open()
signal on_large_suitcase_open()
signal on_pick_up()
signal on_score_update(amount : int)
signal on_complete_case(case : int)
